# Generated by Django 5.2.8 on 2025-11-14 12:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview'), ('rejected', 'Rejected')], default='pending', max_length=50)),
                ('cover_letter', models.TextField()),
                ('resume', models.FileField(upload_to='application_documents/settings.AUTH_USER_MODEL/')),
                ('additional_documents', models.FileField(blank=True, null=True, upload_to='application_documents/settings.AUTH_USER_MODEL/')),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('expected_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('availabilty_date', models.DateField()),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='Date and time when the application was reviewed', null=True)),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs.job')),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['-applied_on'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='applications.application')),
            ],
            options={
                'verbose_name': 'Application Status History',
                'verbose_name_plural': 'Application Status Histories',
            },
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['job'], name='application_job_id_2b6ae2_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['applicant'], name='application_applica_a7c7c2_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status'], name='application_status_1508e0_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['applied_on'], name='application_applied_7d8bb3_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationstatushistory',
            index=models.Index(fields=['application'], name='application_applica_a170d6_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationstatushistory',
            index=models.Index(fields=['status'], name='application_status_39dbfb_idx'),
        ),
    ]
