# Generated by Django 5.2.8 on 2025-11-15 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationstatushistory',
            name='notes',
        ),
    ]
