# Generated by Django 5.2.8 on 2025-11-15 08:31

import applications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_remove_applicationstatushistory_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='availabilty_date',
            new_name='availability_date',
        ),
        migrations.AlterField(
            model_name='application',
            name='additional_documents',
            field=models.FileField(blank=True, null=True, upload_to=applications.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(upload_to=applications.models.user_directory_path),
        ),
    ]
