# Generated by Django 5.2.8 on 2025-11-15 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_alter_application_job'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApplicationStatusHistory',
            new_name='ApplicationHistory',
        ),
        migrations.AlterModelOptions(
            name='applicationhistory',
            options={'verbose_name': 'Application History', 'verbose_name_plural': 'Application Histories'},
        ),
        migrations.RenameIndex(
            model_name='applicationhistory',
            new_name='application_applica_32e9bf_idx',
            old_name='application_applica_a170d6_idx',
        ),
        migrations.RenameIndex(
            model_name='applicationhistory',
            new_name='application_status_7f356b_idx',
            old_name='application_status_39dbfb_idx',
        ),
    ]
