# Generated by Django 5.2.8 on 2025-11-19 10:33

import applications.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_rename_applicationstatushistory_applicationhistory_and_more'),
        ('jobs', '0009_remove_job_jobs_job_categor_24d294_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='application',
            name='job',
        ),
        migrations.RemoveField(
            model_name='application',
            name='reviewed_by',
        ),
        migrations.CreateModel(
            name='ApplyJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview'), ('rejected', 'Rejected')], default='pending', max_length=50)),
                ('cover_letter', models.TextField()),
                ('resume', models.FileField(upload_to=applications.models.user_directory_path)),
                ('additional_documents', models.FileField(blank=True, null=True, upload_to=applications.models.user_directory_path)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('expected_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('availability_date', models.DateField()),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='Date and time when the application was reviewed', null=True)),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apply_job', to='jobs.job')),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['-applied_on'],
            },
        ),
        migrations.AlterField(
            model_name='applicationhistory',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='applications.applyjob'),
        ),
        migrations.AddIndex(
            model_name='applyjob',
            index=models.Index(fields=['job'], name='application_job_id_401bf1_idx'),
        ),
        migrations.AddIndex(
            model_name='applyjob',
            index=models.Index(fields=['applicant'], name='application_applica_a881ba_idx'),
        ),
        migrations.AddIndex(
            model_name='applyjob',
            index=models.Index(fields=['status'], name='application_status_e5193b_idx'),
        ),
        migrations.AddIndex(
            model_name='applyjob',
            index=models.Index(fields=['applied_on'], name='application_applied_b531c1_idx'),
        ),
        migrations.DeleteModel(
            name='Application',
        ),
    ]
