# Generated by Django 5.2.8 on 2025-11-19 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_remove_application_applicant_remove_application_job_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApplicationHistory',
        ),
    ]
