# Generated by Django 5.2.8 on 2025-11-14 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_company_name'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='company',
            new_name='jobs_compan_industr_a8757f_idx',
            old_name='jobs_compan_industr_e7d565_idx',
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(default='No description', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='jobs.category'),
        ),
    ]
