# Generated by Django 5.2.8 on 2025-11-14 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_rename_jobs_compan_industr_e7d565_idx_jobs_compan_industr_a8757f_idx_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Industry',
        ),
    ]
