# Generated by Django 5.2.8 on 2025-11-15 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_rename_category_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='requirements',
            field=models.TextField(help_text='Comma-separated skills'),
        ),
        migrations.AlterField(
            model_name='job',
            name='responsibilities',
            field=models.TextField(help_text='Comma-separated skills'),
        ),
    ]
