# Generated by Django 5.2.8 on 2025-11-15 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_job_requirements_alter_job_responsibilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='region',
            field=models.CharField(default='Kahawa', max_length=100),
            preserve_default=False,
        ),
    ]
