# Generated by Django 5.2.8 on 2025-11-17 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_industry_options_company_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='description',
            field=models.TextField(default='Added manually', max_length=500),
            preserve_default=False,
        ),
    ]
