# Generated by Django 5.2.8 on 2025-11-19 10:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_industry_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='job',
            name='jobs_job_categor_24d294_idx',
        ),
        migrations.RemoveIndex(
            model_name='job',
            name='jobs_job_is_acti_9e9ad0_idx',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='category',
            new_name='industry',
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_currency',
            field=models.CharField(default='Ksh', max_length=3),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['industry'], name='jobs_job_industr_992fec_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['is_active', 'industry'], name='jobs_job_is_acti_f35740_idx'),
        ),
    ]
